version: '3'
services:
  service-app:
    image: service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-postgresql:5432/service
networks:
  consent_net:
    external:
      name: consent_net
