version: '3'
services:
  service-postgresql:
    image: postgres:11.5
    environment:
      - POSTGRES_USER=service
      - POSTGRES_PASSWORD=
networks:
  consent_net:
    external:
      name: consent_net
