version: '3'
services:
  gateway-app:
    image: gateway
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ../../../jssecacerts:/opt/java/openjdk/lib/security/jssecacerts
    ports:
      - 8443:8443
networks:
  default:
    external:
      name: consent_net
