spring:
  application:
    name: eureka
  cloud.loadbalancer.ribbon.enabled: false
eureka:
  instance:
    hostname: eureka-app
    non-secure-port-enabled: false
    secure-port: ${server.port}
    secure-port-enabled: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://eureka-app:8761/eureka/
server:
  port: 8761
  ssl:
    enabled: true
    key-store: classpath:eureka.jks
    key-alias: eureka
    key-store-password: eureka
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
application:
  logging:
    use-json-format: true
    logstash:
      enabled: true
      host: logstash
      port: 5044
      queue-size: 512
