version: '3'
services:
  declaration-app:
    image: declaration
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql-declaration:5432/
    volumes:
      - ../../../jssecacerts:/opt/java/openjdk/lib/security/jssecacerts
networks:
  default:
    external:
      name: consent_net
