version: '3'
services:
  postgresql-declaration:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_USER=declaration
      - POSTGRES_PASSWORD=
    ports:
    - 5432:5432
networks:
  default:
    external:
      name: consent_net
