version: '3'
services:
  eureka-app:
    image: eureka
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
networks:
  consent_net:
    external:
      name: consent_net
